# This docker compose sets up the full environment for all tests (or at least that's the goal)

services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  mongo_replica:
    image: mongo:5.0
    ports:
      - "27018:27017"
    command: mongod --replSet rs0
